defaults:
  useAggregateSpread: 250k
  tickStoreUrl: "bootstrap.ldn.simulation.properties"
  percentile: 0.5
  useAggregateSpread: false

liquidity:
  useAggregateSpread: true
  tickStoreUrl: "bootstrap.ldn.simulation.properties"
  percentile: 0.5
  market: CLIENT_PRICE_NYC
  benchmarkMarkets: EXISTING_PEPPER_POOL
  bootstrapProperties: bootstrap.simulation.properties
  tickStoreUrl: s3://pepperstone-production-tickstore/pepperstone/pepperstone-ny-trading-1.int.p7l0.beeks.prod.mahimarkets.com/starfishFilePersisterExternalMarketData1
  maxVarLevel: 230k
  configurationS3Url: s3://mfx-compass-customer-config/PEPPERSTONE/PEPPERSTONE_config-update.json.gz
