defaults:
  tickStoreUrl: "bootstrap.ldn.simulation.properties"
  mahiLogLevel: INFO

liquidity:
  bootstrapProperties: bootstrap.simulation.properties
  tickStoreUrl: s3://pepperstone-production-tickstore/pepperstone/pepperstone-ny-trading-1.int.p7l0.beeks.prod.mahimarkets.com/starfishFilePersisterExternalMarketData1
  maxVarLevel: 230k
  configurationS3Url: s3://mfx-compass-customer-config/PEPPERSTONE/PEPPERSTONE_config-update.json.gz
