defaults:
  tickStoreUrl: "bootstrap.ldn.simulation.properties"
  mahiLogLevel: INFO

liquidity:
  bootstrapProperties: bootstrap.simulation.properties
  tickStoreS3Bucket: pepperstone-production-tickstore
  tradinghHost: pepperstone-ny-trading-1.int.p7l0.beeks.prod.mahimarkets.com
  maxVarLevel: 230k
  configurationS3Url: s3://mfx-compass-customer-config
